name: Docker Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.**'
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: |
          docker build -t tadayosi/hello-js .
      - name: Push
        run: |
          docker push tadayosi/hello-js
